[build]
  functions = "netlify/functions"
  publish = "."
 
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://api.anthropic.com"
 
